// ===== แก้ตรงนี้ได้ =====
// ข้อความที่จะต่อหน้า/ท้ายทุก prompt ตอนกดคัดลอก (ใส่ชื่อตัวละคร/สไตล์ของตัวเองได้)
// ถ้าไม่ต้องการ ให้เปลี่ยนเป็น "" (ว่าง)
const PREFIX = "cute chibi character, ";
const SUFFIX = ", LINE sticker style, thick outline, simple white background";

// mood ที่ใช้ได้: happy, love, sad, mad, wow, tired  (กำหนดสีการ์ด)
const PROMPTS = [
  { th: "หัวเราะลั่น", en: "Laughing out loud", emoji: "😂", mood: "happy",
    prompt: "laughing out loud, eyes squeezed shut, mouth wide open, holding belly with both hands" },
  { th: "ยิ้มกว้าง", en: "Big smile", emoji: "😄", mood: "happy",
    prompt: "big cheerful smile, bright eyes, waving one hand" },
  { th: "ดีใจสุดๆ", en: "Overjoyed", emoji: "🥳", mood: "happy",
    prompt: "jumping with joy, both arms raised high, confetti around, mouth open in a cheer" },
  { th: "ภูมิใจ", en: "Proud", emoji: "😎", mood: "happy",
    prompt: "proud expression, chest puffed out, chin up, hands on hips, small sparkle" },
  { th: "ตื่นเต้น", en: "Excited", emoji: "🤩", mood: "happy",
    prompt: "sparkling star eyes, fists clenched near chest, bouncing with excitement" },
  { th: "สบายใจ", en: "Content and relaxed", emoji: "😌", mood: "happy",
    prompt: "relaxed content smile, eyes gently closed, shoulders down, soft blush" },
  { th: "สู้ๆ", en: "You can do it", emoji: "💪", mood: "happy",
    prompt: "determined smile, fist pumped in front, other arm flexing, encouraging pose" },
  { th: "โอเค", en: "OK", emoji: "👌", mood: "happy",
    prompt: "friendly smile, making an OK sign with one hand, slight wink" },

  { th: "รักเลย", en: "Heart eyes", emoji: "😍", mood: "love",
    prompt: "heart-shaped eyes, cheeks blushing, hands clasped near cheek, floating hearts" },
  { th: "ส่งจูบ", en: "Blowing a kiss", emoji: "😘", mood: "love",
    prompt: "blowing a kiss with one hand, one eye winking, small heart flying away" },
  { th: "กอด", en: "Hug", emoji: "🤗", mood: "love",
    prompt: "warm smile, both arms wide open ready to hug, slightly leaning forward" },
  { th: "ขอบคุณ", en: "Thank you", emoji: "🙏", mood: "love",
    prompt: "grateful smile, palms pressed together in front of chest, slight bow" },
  { th: "เขิน", en: "Shy and blushing", emoji: "😳", mood: "love",
    prompt: "deeply blushing cheeks, looking away, fingers poking together, embarrassed smile" },
  { th: "อ้อนๆ", en: "Pleading", emoji: "🥺", mood: "love",
    prompt: "big watery puppy eyes, hands clasped under chin, pleading look, tiny pout" },
  { th: "คิดถึง", en: "Missing you", emoji: "💭", mood: "love",
    prompt: "gentle sad smile, hugging a pillow, looking up dreamily, small heart thought bubble" },

  { th: "ร้องไห้โฮ", en: "Sobbing", emoji: "😭", mood: "sad",
    prompt: "sobbing loudly, streams of tears flowing, mouth wide open, wiping eyes with fists" },
  { th: "น้ำตาคลอ", en: "Teary-eyed", emoji: "🥲", mood: "sad",
    prompt: "eyes welling with tears, trembling lips, forced small smile" },
  { th: "เสียใจ", en: "Sad", emoji: "😢", mood: "sad",
    prompt: "sad expression, head lowered, downturned mouth, one tear rolling down" },
  { th: "น้อยใจ", en: "Sulking", emoji: "😞", mood: "sad",
    prompt: "sulking, puffed cheeks, arms crossed, looking away, small storm cloud above head" },
  { th: "ท้อ", en: "Discouraged", emoji: "😩", mood: "sad",
    prompt: "slumped shoulders, head hanging, arms dangling, dark gloomy lines above head" },
  { th: "เหงา", en: "Lonely", emoji: "🌧️", mood: "sad",
    prompt: "sitting alone hugging knees, looking down, small rain cloud overhead" },
  { th: "ขอโทษ", en: "Sorry", emoji: "🙇", mood: "sad",
    prompt: "deep apologetic bow, hands pressed together, worried eyes, sweat drop" },

  { th: "โกรธ", en: "Angry", emoji: "😡", mood: "mad",
    prompt: "furious face, furrowed eyebrows, clenched fists, steam puffing from head" },
  { th: "หงุดหงิด", en: "Annoyed", emoji: "😒", mood: "mad",
    prompt: "annoyed side-eye, flat mouth, one eyebrow raised, arms crossed" },
  { th: "เบื่อ", en: "Bored", emoji: "😑", mood: "mad",
    prompt: "deadpan bored face, half-lidded eyes, cheek resting on hand, flat mouth" },
  { th: "ไม่เอา", en: "No way", emoji: "🙅", mood: "mad",
    prompt: "shaking head, arms crossed in an X in front of chest, firm frown" },
  { th: "ตกใจกลัว", en: "Scared", emoji: "😱", mood: "mad",
    prompt: "terrified face, trembling, hands on cheeks, wide eyes, blue shiver lines" },

  { th: "ตกใจ", en: "Shocked", emoji: "😲", mood: "wow",
    prompt: "jaw dropped, wide round eyes, both hands raised in surprise, exclamation mark above head" },
  { th: "อึ้ง", en: "Speechless", emoji: "😶", mood: "wow",
    prompt: "speechless, blank stare, tiny dot mouth, big sweat drop, frozen stiff pose" },
  { th: "งง", en: "Confused", emoji: "🤔", mood: "wow",
    prompt: "confused look, head tilted, scratching head, question marks floating around" },
  { th: "คิดอยู่", en: "Thinking", emoji: "🧐", mood: "wow",
    prompt: "thinking hard, hand on chin, eyes looking up to the side, small thought bubble" },
  { th: "ได้ไอเดีย", en: "Got an idea", emoji: "💡", mood: "wow",
    prompt: "sudden realization, finger raised, glowing lightbulb above head, wide bright eyes" },
  { th: "ขยิบตา", en: "Wink", emoji: "😉", mood: "wow",
    prompt: "playful wink, one eye closed, finger gun pose, small star sparkle" },
  { th: "แลบลิ้น", en: "Tongue out", emoji: "😜", mood: "wow",
    prompt: "sticking tongue out, one eye winking, silly playful pose, pulling down eyelid" },
  { th: "ยิ้มเจ้าเล่ห์", en: "Smug", emoji: "😏", mood: "wow",
    prompt: "smug smirk, half-closed eyes, one eyebrow raised, sly grin, hand near chin" },

  { th: "ง่วง", en: "Sleepy", emoji: "🥱", mood: "tired",
    prompt: "big yawn, droopy eyelids, rubbing one eye, tiny tear at corner" },
  { th: "หลับ", en: "Sleeping", emoji: "😴", mood: "tired",
    prompt: "fast asleep, eyes closed, snot bubble, floating Zzz, head nodding" },
  { th: "เพิ่งตื่น", en: "Just woke up", emoji: "🛏️", mood: "tired",
    prompt: "just woke up, messy bedhead hair, half-open sleepy eyes, stretching one arm up" },
  { th: "เหนื่อย", en: "Exhausted", emoji: "😮‍💨", mood: "tired",
    prompt: "exhausted, deep sigh with a puff of air, slouched body, dark circles under eyes" },
  { th: "หิว", en: "Hungry", emoji: "🤤", mood: "tired",
    prompt: "very hungry, drooling, hands on empty stomach, sparkling eyes staring at food" },
];